version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/{{cookiecutter.component_id}}" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - BESTSELLER/engineering-services
